//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquashNext.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BookingRule
    {
        public BookingRule()
        {
            this.Bookings = new HashSet<Booking>();
        }
        [Display(Name = "Booking Rules Id")]
        public int bookingRuleId { get; set; }
        [Display(Name = "Organization")]
        public int organizationID { get; set; }
        [Display(Name = "Days In Advance Allowed")]
        public int daysInAdvance { get; set; }
        [Display(Name = "Number of Bookings Allowed")]
        public int numOfBookings { get; set; }
        [Display(Name = "Number of Missed Booking Strikes")]
        public int numOfStrikes { get; set; }
        [Display(Name = "Day Start")]
        public System.TimeSpan dayStart { get; set; }
        [Display(Name = "Booking Length")]
        public int bookingLength { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
