//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquashNext.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Building
    {
        public Building()
        {
            this.Bookings = new HashSet<Booking>();
            this.Courts = new HashSet<Court>();
        }
        [Display(Name = "Building")]
        public int buildingId { get; set; }
        [Display(Name = "Address")]
        public string address { get; set; }
        [Display(Name = "Organization")]
        public int organizationId { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Court> Courts { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
